const condition = {
    1000: { code: 1000, day: "Sunny", night: "Clear", icon: 113, category: 1 },
    1003: {
        code: 1003,
        day: "Partly cloudy",
        night: "Partly cloudy",
        icon: 116,
        category: 2,
    },
    1006: {
        code: 1006,
        day: "Cloudy",
        night: "Cloudy",
        icon: 119,
        category: 2,
    },
    1009: {
        code: 1009,
        day: "Overcast",
        night: "Overcast",
        icon: 122,
        category: 2,
    },
    1030: { code: 1030, day: "Mist", night: "Mist", icon: 143, category: 2 },
    1063: {
        code: 1063,
        day: "Patchy rain possible",
        night: "Patchy rain possible",
        icon: 176,
        category: 3,
    },
    1066: {
        code: 1066,
        day: "Patchy snow possible",
        night: "Patchy snow possible",
        icon: 179,
        category: 6,
    },
    1069: {
        code: 1069,
        day: "Patchy sleet possible",
        night: "Patchy sleet possible",
        icon: 182,
        category: 7,
    },
    1072: {
        code: 1072,
        day: "Patchy freezing drizzle possible",
        night: "Patchy freezing drizzle possible",
        icon: 185,
        category: 7,
    },
    1087: {
        code: 1087,
        day: "Thundery outbreaks possible",
        night: "Thundery outbreaks possible",
        icon: 200,
        category: 8,
    },
    1114: {
        code: 1114,
        day: "Blowing snow",
        night: "Blowing snow",
        icon: 227,
        category: 6,
    },
    1117: {
        code: 1117,
        day: "Blizzard",
        night: "Blizzard",
        icon: 230,
        category: 1,
    },
    1135: { code: 1135, day: "Fog", night: "Fog", icon: 248, category: 3 },
    1147: {
        code: 1147,
        day: "Freezing fog",
        night: "Freezing fog",
        icon: 260,
        category: 7,
    },
    1150: {
        code: 1150,
        day: "Patchy light drizzle",
        night: "Patchy light drizzle",
        icon: 263,
        category: 4,
    },
    1153: {
        code: 1153,
        day: "Light drizzle",
        night: "Light drizzle",
        icon: 266,
        category: 4,
    },
    1168: {
        code: 1168,
        day: "Freezing drizzle",
        night: "Freezing drizzle",
        icon: 281,
        category: 4,
    },
    1171: {
        code: 1171,
        day: "Heavy freezing drizzle",
        night: "Heavy freezing drizzle",
        icon: 284,
        category: 7,
    },
    1180: {
        code: 1180,
        day: "Patchy light rain",
        night: "Patchy light rain",
        icon: 293,
        category: 4,
    },
    1183: {
        code: 1183,
        day: "Light rain",
        night: "Light rain",
        icon: 296,
        category: 4,
    },
    1186: {
        code: 1186,
        day: "Moderate rain at times",
        night: "Moderate rain at times",
        icon: 299,
        category: 5,
    },
    1189: {
        code: 1189,
        day: "Moderate rain",
        night: "Moderate rain",
        icon: 302,
        category: 5,
    },
    1192: {
        code: 1192,
        day: "Heavy rain at times",
        night: "Heavy rain at times",
        icon: 305,
        category: 5,
    },
    1195: {
        code: 1195,
        day: "Heavy rain",
        night: "Heavy rain",
        icon: 308,
        category: 5,
    },
    1198: {
        code: 1198,
        day: "Light freezing rain",
        night: "Light freezing rain",
        icon: 311,
        category: 5,
    },
    1201: {
        code: 1201,
        day: "Moderate or heavy freezing rain",
        night: "Moderate or heavy freezing rain",
        icon: 314,
        category: 5,
    },
    1204: {
        code: 1204,
        day: "Light sleet",
        night: "Light sleet",
        icon: 317,
        category: 7,
    },
    1207: {
        code: 1207,
        day: "Moderate or heavy sleet",
        night: "Moderate or heavy sleet",
        icon: 320,
        category: 7,
    },
    1210: {
        code: 1210,
        day: "Patchy light snow",
        night: "Patchy light snow",
        icon: 323,
        category: 6,
    },
    1213: {
        code: 1213,
        day: "Light snow",
        night: "Light snow",
        icon: 326,
        category: 6,
    },
    1216: {
        code: 1216,
        day: "Patchy moderate snow",
        night: "Patchy moderate snow",
        icon: 329,
        category: 6,
    },
    1219: {
        code: 1219,
        day: "Moderate snow",
        night: "Moderate snow",
        icon: 332,
        category: 6,
    },
    1222: {
        code: 1222,
        day: "Patchy heavy snow",
        night: "Patchy heavy snow",
        icon: 335,
        category: 6,
    },
    1225: {
        code: 1225,
        day: "Heavy snow",
        night: "Heavy snow",
        icon: 338,
        category: 6,
    },
    1237: {
        code: 1237,
        day: "Ice pellets",
        night: "Ice pellets",
        icon: 350,
        category: 12,
    },
    1240: {
        code: 1240,
        day: "Light rain shower",
        night: "Light rain shower",
        icon: 353,
        category: 9,
    },
    1243: {
        code: 1243,
        day: "Moderate or heavy rain shower",
        night: "Moderate or heavy rain shower",
        icon: 356,
        category: 9,
    },
    1246: {
        code: 1246,
        day: "Torrential rain shower",
        night: "Torrential rain shower",
        icon: 359,
        category: 9,
    },
    1249: {
        code: 1249,
        day: "Light sleet showers",
        night: "Light sleet showers",
        icon: 362,
        category: 11,
    },
    1252: {
        code: 1252,
        day: "Moderate or heavy sleet showers",
        night: "Moderate or heavy sleet showers",
        icon: 365,
        category: 11,
    },
    1255: {
        code: 1255,
        day: "Light snow showers",
        night: "Light snow showers",
        icon: 368,
        category: 10,
    },
    1258: {
        code: 1258,
        day: "Moderate or heavy snow showers",
        night: "Moderate or heavy snow showers",
        icon: 371,
        category: 10,
    },
    1261: {
        code: 1261,
        day: "Light showers of ice pellets",
        night: "Light showers of ice pellets",
        icon: 374,
        category: 12,
    },
    1264: {
        code: 1264,
        day: "Moderate or heavy showers of ice pellets",
        night: "Moderate or heavy showers of ice pellets",
        icon: 377,
        category: 12,
    },
    1273: {
        code: 1273,
        day: "Patchy light rain with thunder",
        night: "Patchy light rain with thunder",
        icon: 386,
        category: 4,
    },
    1276: {
        code: 1276,
        day: "Moderate or heavy rain with thunder",
        night: "Moderate or heavy rain with thunder",
        icon: 389,
        category: 5,
    },
    1279: {
        code: 1279,
        day: "Patchy light snow with thunder",
        night: "Patchy light snow with thunder",
        icon: 392,
        category: 6,
    },
    1282: {
        code: 1282,
        day: "Moderate or heavy snow with thunder",
        night: "Moderate or heavy snow with thunder",
        icon: 395,
        category: 6,
    },
};

const style = {
    1: "bg-gradient-to-r from-yellow-400/30 to-orange-300/30",
    2: "bg-gradient-to-r from-gray-300/30 to-gray-500/30",
    3: "bg-gradient-to-r from-slate-300/30 to-slate-500/30",
    4: "bg-gradient-to-r from-blue-300/30 to-blue-500/30",
    5: "bg-gradient-to-r from-indigo-500/30 to-indigo-700/30",
    6: "bg-gradient-to-r from-blue-100/30 to-gray-200/30",
    7: "bg-gradient-to-r from-cyan-200/30 to-cyan-400/30",
    8: "bg-gradient-to-r from-purple-600/30 to-yellow-300/30",
    9: "bg-gradient-to-r from-blue-400/30 to-teal-400/30",
    10: "bg-gradient-to-r from-sky-200/30 to-slate-300/30",
    11: "bg-gradient-to-r from-cyan-300/30 to-gray-300/30",
    12: "bg-gradient-to-r from-blue-200/30 to-indigo-300/30",
    13: "bg-gradient-to-r from-emerald-300/30 to-blue-400/30",
};
console.log(newObj);
